name: dump_viz
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dump-info-visualizer/
description: A visualizer for the JSON data produced by the dart2js --dump-info command
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.11.0 <0.12.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
    - --dump-info
