name: DumpVis
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.11.0 <0.12.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    commandLineOptions: [--dump-info]
    minify: false
